# name: CI/CD to Firebase Hosting

# on:
#   push:
#     branches: [ 59DeployApp ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build (not production)
#       run: |
#         npm install
#         npm run build
#     - name: Deploy
#       run: |
#         sudo npm install -g firebase-tools
#         firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

name: CI/CD to Firebase Hosting

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build (not production)
      run: |
        npm install
        npm run build
    - name: Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}